name: main
on: [push, pull_request]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go test ./... -tags=unit
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.1"
  security-scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        with:
          args: -exclude-dir pkg/test-utils ./...
  golang-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.43
